<script setup lang="ts">
import{computed,ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{api}from'../../api';import type{Address,Cart}from'../../types'
interface Settlement{productAmount:number;deliveryFee:number;discount:number;payableAmount:number}
const address=ref<Address>(),cart=ref<Cart>(),mode=ref<'instant'|'scheduled'>('instant'),slot=ref('20:00-21:00'),settlement=ref<Settlement>(),submitting=ref(false),slots=ref<Array<{id:string;label:string;available:boolean}>>([])
const payload=computed<Record<string,unknown>>(()=>({addressId:address.value?.id,deliveryMode:mode.value,deliverySlot:mode.value==='scheduled'?slot.value:undefined,couponId:'coupon-001'}))
async function refresh(){settlement.value=await api.checkout(payload.value)}
onShow(async()=>{const[a,c,s]=await Promise.all([api.addresses(),api.cart(),api.slots()]);const selected=uni.getStorageSync('selectedAddressId');address.value=a.find(item=>item.id===selected)||a[0];cart.value=c;slots.value=s;await refresh()})
async function setMode(value:'instant'|'scheduled'){mode.value=value;await refresh()}
async function selectSlot(label:string,available:boolean){if(!available)return;slot.value=label;await refresh()}
async function submit(){if(submitting.value)return;submitting.value=true;try{const created=await api.createOrder(payload.value);const paid=await api.payOrder(created.id);uni.redirectTo({url:`/pages/orders/detail?id=${paid.id}`})}finally{submitting.value=false}}
</script>
<template><view class="page checkout"><view v-if="address" class="address card" @tap="uni.navigateTo({url:'/pages/address/index'})"><text class="address__flag">送到这里</text><text class="address__room">{{address.buildingName}} · {{address.room}} 寝室</text><text class="muted">{{address.contactName}} {{address.phone}}　›</text></view><view class="section-title"><text class="section-title__main">怎么送到寝</text></view><view class="modes"><view class="mode card" :class="{'mode--active':mode==='instant'}" @tap="setMode('instant')"><text class="mode__title">立即配送</text><text class="mode__time">30-60 分钟</text><text class="muted">现在就想要</text></view><view class="mode card" :class="{'mode--active':mode==='scheduled'}" @tap="setMode('scheduled')"><text class="mode__title">省心送达</text><text class="mode__time">2 小时内</text><text class="muted">运费更省</text></view></view><view v-if="mode==='scheduled'" class="slots card"><text class="slots__title">选择时间</text><view v-for="s in slots" :key="s.id" class="slot" :class="{'slot--active':slot===s.label,'slot--disabled':!s.available}" @tap="selectSlot(s.label,s.available)">{{s.label}}</view></view><view class="section-title"><text class="section-title__main">这袋有这些</text></view><view class="goods card"><view v-for="line in cart?.items" :key="line.product.id" class="goods__line"><image :src="line.product.image" mode="aspectFit"/><text>{{line.product.name}} × {{line.quantity}}</text><text>¥{{(line.product.price*line.quantity).toFixed(2)}}</text></view></view><view v-if="settlement" class="bill card"><view><text>商品金额</text><text>¥{{settlement.productAmount}}</text></view><view><text>配送费</text><text>¥{{settlement.deliveryFee}}</text></view><view class="bill__coupon"><text>新同学首单券</text><text>−¥{{settlement.discount}}</text></view><view class="bill__total"><text>合计</text><text>¥{{settlement.payableAmount}}</text></view></view><view class="submit safe-bottom"><view><text class="muted">微信支付（Mock）</text><text class="submit__price">¥{{settlement?.payableAmount||'--'}}</text></view><button class="primary-btn" :disabled="submitting" @tap="submit">{{submitting?'正在支付…':'确认支付'}}</button></view></view></template>
<style scoped lang="scss">@import '../../styles/theme.scss';.address{padding:30rpx;border-top:8rpx solid $primary}.address__flag{display:block;color:$primary-dark;font-size:22rpx;font-weight:800}.address__room{display:block;font-size:36rpx;font-weight:900;margin:10rpx 0}.modes{display:grid;grid-template-columns:1fr 1fr;gap:20rpx}.mode{padding:26rpx;border:4rpx solid transparent}.mode--active{border-color:$primary;background:#fff5ed}.mode__title,.mode__time{display:block}.mode__title{font-weight:900}.mode__time{font-size:32rpx;font-weight:900;margin:12rpx 0}.slots{display:flex;align-items:center;gap:12rpx;margin-top:20rpx;padding:22rpx;overflow:hidden}.slots__title{font-weight:800}.slot{padding:14rpx;border:2rpx solid $line;border-radius:18rpx;font-size:21rpx}.slot--active{background:$ink;color:#fff}.slot--disabled{opacity:.35;text-decoration:line-through}.goods{padding:12rpx 24rpx}.goods__line{display:grid;grid-template-columns:80rpx 1fr auto;align-items:center;gap:16rpx;padding:16rpx 0;border-bottom:2rpx solid $line}.goods__line image{width:80rpx;height:80rpx}.bill{margin-top:22rpx;padding:26rpx}.bill>view{display:flex;justify-content:space-between;padding:12rpx}.bill__coupon{color:$primary-dark}.bill__total{border-top:2rpx dashed $line;margin-top:12rpx;padding-top:24rpx!important;font-weight:900;font-size:34rpx}.submit{position:fixed;left:0;right:0;bottom:0;background:#fff;padding:18rpx 28rpx;display:flex;align-items:center;justify-content:space-between;box-shadow:0 -10rpx 30rpx rgba(47,38,34,.08)}.submit__price{display:block;font-size:40rpx;font-weight:900;color:$primary-dark}.submit .primary-btn{width:300rpx;margin:0}</style>
